unset PYTHONPATH
unset CONDA_SHLVL
unset CONDA_PROMPT_MODIFIER
unset CONDA_EXE
unset CONDA_PREFIX
unset CONDAHOME
unset CONDA_PYTHON_EXE
unset CONDA_DEFAULT_ENV
export PATH=/work/ALT/odatis/briolf/anaconda3/bin:$PATH
